## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file sagetex_simple_101.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_14 = Integer(14); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_19 = Integer(19); _sage_const_21 = Integer(21); _sage_const_23 = Integer(23); _sage_const_26 = Integer(26); _sage_const_2 = Integer(2)## This file (sagetex_simple_101.sagetex.sage) was *autogenerated* from sagetex_simple_101.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('sagetex_simple_101', version='2020/08/12 v3.5', version_check=True)
_st_.current_tex_line = _sage_const_14 
_st_.blockbegin()
try:
 _sage_const_1 +_sage_const_1 
 var('a,b,c')
 eqn = [a+b*c==_sage_const_1 , b-a*c==_sage_const_0 , a+b==_sage_const_5 ]
 s = solve(eqn, a,b,c)
except:
 _st_.goboom(_sage_const_19 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_21 
 _st_.inline(_sage_const_0 , latex(eqn))
except:
 _st_.goboom(_sage_const_21 )
try:
 _st_.current_tex_line = _sage_const_23 
 _st_.inline(_sage_const_1 , latex(s[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_23 )
try:
 _st_.current_tex_line = _sage_const_26 
 _st_.inline(_sage_const_2 , latex(s[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_26 )
_st_.endofdoc()

