values;

usefastarrays:true; use_fast_arrays:true;

/* DEFINING INFO STRUCTURES AND TABLES [HASH ARRAYS] */

defstruct(var_info(name,value,latex));

defstruct(fun_info(ftyp,name,fargs,body,latex));

usefastarrays:true;

defstruct(var_table(count,vars));

defstruct(fun_table(count,funs));

/* MANUAL OPERATIONS USING STRUCTURES AND HASH ARRAYS */

vinfo_ch01:new(var_info);

vinfo_ch01@name:P_p1_s;

vinfo_ch01@value:0.0531;

vinfo_ch01@latex:[['math,"P_{\\scriptscriptstyle{[+1,s]}}"],['text,"P_{[+1,s]}"]];

assoc('math,vinfo_ch01@latex);

assoc('text,vinfo_ch01@latex);

vch01_ltx:assoc(math,vinfo_ch01@latex);

vch01_ltx;

vtab_ch01:new(var_table);

vtab_ch01@vars:[vinfo_ch01];

vtab_ch01@count:1;

finfo_Pv_z:new(fun_info);

finfo_Pv_z@ftyp:"FUN";

finfo_Pv_z@name:P_v;

finfo_Pv_z@fargs:[z];

finfo_Pv_z@body:"abs(w_v)*sum(p_m*abs(a_vm(z))^2,m,minf,inf)";

finfo_Pv_z@latex:"P_\\nu(z)~=~\\left| \\omega_\\nu \\right|~\\sum_{-\\infty}^{\\infty}~p_{m}~\\left|~a_{-\\nu}~(z)\\right|^2";

ftab_ch01:new(fun_table);

ftab_ch01@count:1;

ftab_ch01@funs:[finfo_Pv_z];

finfo_Pdz_z:new(fun_info);

finfo_Pdz_z@ftyp:"FUN";

finfo_Pdz_z@name:P_dz;

finfo_Pdz_z@fargs:[z];

finfo_Pdz_z@body:"diff(sum(q_v*p_m*abs(a_vm(z))^2,m,minf,inf),z)";

finfo_Pdz_z@latex:"P_{dz}(z)~= ~\\left|~\\omega_\\nu~\\right|~\\sum_{-\\infty}^{\\infty}~p_{m}~\\left|~a_{-\\nu}~(z)\\right|^2";

finfo_S_w0:new(fun_info); finfo_S_w0@name:'finfo_S_w0;

finfo_S_w0;

finfo_S_w0@body:"A* sin(w_0*t+phi)";

finfo_S_w0@fargs: [A,w_0,t,phi];

finfo_S_w0@ftyp:"SYMBOLIC";

finfo_S_w0;

finfo_S_w0@latex: "S(A, \\omega_0, t, \\phi)=A \\cdot sin(\\omega_0 \\cdot t + \\phi)";

arr_funs[finfo_S_w0@name]:finfo_S_w0;

arr_funs['finfo_S_w0]@latex;

tf01@body;

finfo_S_w0@body;

fp:[['ftyp, "SYMBOLIC"],['name,'Ak_A0_kA_z],['fargs, [A_0,k_A,z]],['body, "(A_0/z)*sin(k_a*z)*exp(-%i*z/4*%pi)"],['latex, "\\frac{A_{0}}{z}\\,sin(k_a~z)~e^{\\left( \\frac{-i~\\pi~z}{4}\\right)}"] ]  ;

assoc('latex,fp);

arr_funs['finfo_S_w0]@latex;

arr_funs['Ak_A0_kAz];

/* DEFINING FUNCTIONS TO ADD STRUCTURES TO HASH ARRAYS USING FUNCTION 

NAME AS HASH KEY FOR LOOKUP. WORKS WELL AND SEEMS FAST ENOUGH FOR TESTING

COMPILE ALL CODE TO LISP ONCE IT WORKS - BETTER PERFORMANCE RESULTS

ftyp FIELD - FOR NOW USE IT FOR NUMERIC OR SYMBOLIC
 */

make_finfo(fl):=new(fun_info(''assoc('ftyp, fl),''assoc('name,fl),''assoc('fargs,fl),''assoc('body,fl),''assoc('latex,fl))) ;

add_fun(fl):=arr_funs[assoc('name,fl)]:make_finfo(fl);

/* ADDING ITEMS WITH add_fun  */

add_fun([['ftyp, "SYMBOLIC"] , ['name,'E_r_t_z_t] , ['fargs, [r_t,z,t]] , ['body, "sum(A_k(A_0,k_A,z)*E_k(r_t)*exp(%i*ω*t-γ_k*z),k,minf,inf)"] , ['latex,  "E(r_t,z,t)~=~\\sum_{k=-\\infty}^{ \\infty}A_k(A_0,k_A,z)~E_k(r_t)~e^{ \\left( i \\omega t-\\gamma_k z\\right) }"]]);

arr_funs[E_r_t_z_t];

arr_funs[E_r_t_z_t]@name;

arr_funs[E_r_t_z_t]@ftyp;

arr_funs[E_r_t_z_t]@fargs;

arr_funs[E_r_t_z_t]@body;

arr_funs[E_r_t_z_t]@latex;

add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1242_A] , ['fargs, [z]] , ['body, "sum(P_vm(z), m, minf,inf)"] , ['latex, "P_v(z)=\\sum_{m=-\\infty}^{\\infty}P_{vm}(z)"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1242_B] , ['fargs, [z]] , ['body, "abs(w_v)*sum(p_m*abs(a_vm(z))^2,m,minf,inf)"] , ['latex, "P^{\\left( \\nu \\right)}(z)=\\left|w_v \\right| \\sum_{m=-\\infty}^{\\infty}p_m~\\left|a_m^{\\left(\\nu\\right)}(z)\\right|^2"]]);

arr_funs[EQ_1242_B];

arr_funs[EQ_1242_B]@ftyp;

arr_funs[EQ_1242_B]@name;

arr_funs[EQ_1242_B]@fargs;

arr_funs[EQ_1242_B]@body;

add_fun([['ftyp, "SYMBOLIC"] , ['name,'E_r_t_z_t] , ['fargs, [r_t,z,t]] , ['body, "sum(A_k(A_0,k_A,z)*E_k(r_t)*exp(%i*ω*t-γ_k*z),k,minf,inf)"] , ['latex,  "E(r_t,z,t)~=~\\sum_{k=-\\infty}^{ \\infty}A_k(A_0,k_A,z)~E_k(r_t)~e^{ \\left( i~\\omega~t-\\gamma_k z\\right) }"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'H_r_t_z_t] , ['fargs, [r_t,z,t]] , ['body, "sum(A_k(A_0,k_A,z)*H_k(r_t)*exp(%i*ω*t-γ_k*z),k,minf,inf)"] , ['latex,  "H(r_t,z,t)~=~\\sum_{k=-\\infty}^{ \\infty}A_k(A_0,k_A,z)~H_k(r_t)~e^{ \\left( i \\omega~t-\\gamma_k z\\right) }"]]);

add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_3217_A] , ['fargs, [I_P,N]] , ['body, "(1/2)*avg_t(E.'diff(P,t)"] , ['latex,  "\\big\\langle~I_P~\\big\\rangle=\\frac{1}{2}~\\bigg\\langle~E\\cdot\\frac{\\partial{P}}{\\partial{t}}-P\\cdot\\frac{\\partial{E}}{\\partial{t}}\\bigg\\rangle"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_3217_B] , ['fargs, [I_P,N]] , ['body, "avg_t(I_P,N)=(1/2)*avg_t(E.'diff(D,t)-D.'diff(E,t),N)"] , ['latex, "\\big\\langle~I_P~\\big\\rangle = \\frac{1}{2}\\bigg\\langle~E~\\cdot \\frac{\\partial{D}}{\\partial{t}}~-~D \\cdot \\frac{\\partial{E}}{\\partial{t}}~\\bigg\\rangle"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_3217_C] , ['fargs, [I_P,N]] , ['body, "avg_t(I_P,N)=(1/4)*'realpart('conjugate(E).(%i*ω*D)-'conjugate(D).(%i*ω*E))"] , ['latex, "\\big\\langle~I_P~\\big\\rangle~=~\\frac{1}{4}~Re~\\big\\{~E^{*}~\\cdot~\\left(i~\\omega~D~\\right)~-~D^{*}~\\cdot~\\left(~i~\\omega~E~\\right)~\\big\\}"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_3217_D] , ['fargs, [I_P,N]] , ['body, "avg_t(I_P,N)=(1/4)*'realpart(%i*'ω*('conjugate(E).ε_bar.E+'conjugate(E)*ξ_bar.H-E.'conjugate(ε_bar).'conjugate(E)-E.'conjugate(ξ_bar).'conjugate(H)))"] , ['latex, "\\big\\langle~I_P~\\big\\rangle~=~\\frac{1}{2}~Re~\\big\\{~i~\\omega~\\left(~\\bar{\\epsilon}^{ a}~:~EE^{*}~+~\\xi~:~HE^{*}~\\right)~\\big\\}"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_3217_E] , ['fargs, [I_P,N]] , ['body, "avg_t(I_P,N)=(1/4)*'realpart(%i*ω*('conjugate(E).(ε_bar-'conjugate(ε_bar)).E+2*'conjugate(E)-E.'conjugate(ξ_bar).'conjugate(H)))"] , ['latex, "\\big\\langle~I_P~\\big\\rangle~=~\\frac{1}{4}~Re~\\big\\{~i~\\omega~\\big[~E^{*}~\\cdot~\\left(~\\bar{\\epsilon}~-~\\bar{\\epsilon}^{\\dagger}~\\right)~\\cdot~E~+~2~E^{*}~\\cdot~\\bar{\\xi}~\\cdot~H~\\big]~\\big\\}"]]);

add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_3217_F] , ['fargs, [I_P,N]] , ['body, "avg_t(I_P,N)=(1/2)*'realpart(%i*ω*('conjugate(ε_bar).E.'conjugate(E))+ε_bar.H.'conjugate(E))"] , ['latex, "\\big\\langle~I_P~\\big\\rangle~=~\\frac{1}{2}~Re~\\big\\{~i~\\omega\\left(~\\bar{\\epsilon}^{  a}~:~EE^{*}~+~\\xi~:~HE^{*}~\\right)~\\big\\}" ]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,EQ_1243_A] , ['fargs, [z]] , ['body, "'diff(sum(q_v*p_m*abs(a_vm(z))^2,m,minf,inf),z)"] , ['latex, "P_{dz}\\left(z\\right)=\\frac{\\partial}{\\partial{z}}\\sum_{m=-\\infty}^{\\infty} q_v~p_m \\left| a_m^{\\left(\\nu\\right)}\\right|^2"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1243_B] , ['fargs, [z]] , ['body, "w_v(q_v,w,v,w_p):=q_v*(w + v*w_p)" ] , ['latex, "\\omega_{\\nu}~\\left(~q_{\\nu},\\omega~\\right)~~=~q_{\\nu}~\\left(~\\omega~+~\\nu~\\omega_p~\\right)"]]);

            

add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1244_B] , ['fargs, [q_v]] , ['body, "q_v=(w_w+v*w_p)/(abs(w+v*w_p))" ] , ['latex, "q_{\\nu}=\\frac{\\omega_{\\nu}+\\nu~\\omega_p}{\\left|\\omega+\\nu\\omega_p\\right|}"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1244_C] , ['fargs, [w_v]] , ['body, "if w_v >0 then q_v=+1" ] , ['latex, "if~w_{\\nu} > 0~then~q_{\\nu}=+1"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1244_D] , ['fargs, [w_v]] , ['body, "if w_v < 0 then q_v=-1" ] , ['latex, "if~w_{\\nu} < 0~then~q_{\\nu}=-1"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1245] , ['fargs, [N_m]] , ['body, "abs(N_m)=4" ] , ['latex, "if~w_{\\nu} < 0~then~q_{\\nu}=-1"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1246] , ['fargs, [N_m]] , ['body, "P_m(z):=p_m*abs(a_vm(z))^2" ],['latex, 
            "P_m \\left( z \\right) = p_m~\\left| a_m^{\\left( \\nu \\right) } \\right|^2"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1247_A] , ['fargs, [z]] , ['body, "P(z):='sum(P_m(z),m,minf,inf)" ] , ['latex, "P \\left( z \\right) = \\sum_{m=-\\infty}^{\\infty}P_m \\left(z\\right)"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1247_B] , ['fargs, [z]] , ['body, "P(z):='sum(p_m*abs(a_vm(z))^2,m,minf,inf)" ] , ['latex, "P \\left( z \\right) = \\sum_{m=-\\infty}^{\\infty}p_m \\left|a_m^{\\left( \\nu \\right)} \\right|^2 \\left( z \\right)"]]);


add_fun([['ftyp, "SYMBOLIC"] , ['name,'EQ_1248] , ['fargs, [z]] , ['body, "D_Pz(z):='diff(sum(p_m * abs(a_vm(z))^2,m,minf,inf),z) = 0" ] , ['latex, "D_{P_z}\\left( z \\right) = \\frac{\\partial}{\\partial{z}}\\sum_{m=-\\infty}^{\\infty}\\left| a_m^{\\left( \\nu \\right)}  \\right|^2"]]);




